### ISSUE TITLE
Query : Is it possible to use gulp-angular-protractor with wdio and mocha

### ISSUE THREAD

**Issue by rahulmr** [rochejul/gulp-angular-protractor#32]
I was wondering whether it is possible to use gulp-angular-protractor to work with webdriverio (wdio) and mocha.
gulp-angular-protractor to start-stop appium and wdio with wdio.conf.js and mocha to execute the tests

**Comment by rochejul** [comment]
Hi

Protractor overrides the Jasmine logic to simulate synchronous exeuctions of the Selenium WebDriver (but in real, it will create a promise pipes and execute it asynchronously. So we cannot put some break point, except if we use the promise way)

However, I remember that they try too to allow using Mocha.

For webDriverIO, I think this is not compatible to mix with Protractor, because it seems they have their own lifecycle

Maybe you use instead directly the Selenium WebDriver Api via Protractor if needed ? For example, you could retrieve the Selenium WebDriver Element: http://www.protractortest.org/#/api?view=ElementFinder.prototype.getWebElement

And use the Selenium NodeJs WebDriver API: http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebElement.html

Regards

**Comment by rahulmr** [comment]
Yes webdriverio have their own way of automation and they do not support protractor bindings. Actually, what I was thinking is implementing `wdio-appium-service ` they way you have implement start stop here. I just want to use this repo to start the appium server before tests and stop it after tests are done.

I am personally used the onPrepare and onComplete functions in wdio.conf.js file to do the same but having some difficulty there while trying to kill the process after execution is completed.

**Comment by rochejul** [comment]
Hi

Have you more feedbacks to give for this issue please ?

Many thanks
